Feature/base file structure and styles
tihon-veliar/PET-currency-converter pull request #4
Opened 2024-02-21 19:17 UTC by Dmytro1918

Font was added. Structured files iaw SMACSS.

2024-02-21 19:24 UTC, tihon-veliar commented on src/styles/base/variable.scss
> +$background-color:#F3F2EA;
Please, rename this color name. 
We don't have a base color of the bg for the project.
Please, name all colors by their name.

2024-02-21 19:25 UTC, tihon-veliar commented on src/styles/base/variable.scss
We need to use a css variable, not the scss. 
Scss var doesn't work for the styled component.

2024-02-21 19:27 UTC, tihon-veliar commented on src/styles/base/variable.scss
> +$first-title-fontsize:258px;
Font sizes will be flexible, so we don't need vars for them.

2024-02-21 19:28 UTC, tihon-veliar commented on src/styles/base/reset.css
Please, find a reset code for this project.

2024-02-21 19:31 UTC, tihon-veliar commented on src/styles/styles.scss
> +@import 'base/reset';
reset must be in the first place.

2024-02-21 19:33 UTC, tihon-veliar commented on src/styles/styles.scss
This file is better to name as main.scss.

2024-02-21 19:34 UTC, tihon-veliar requested changes
Please, take a look at my comments.

2024-02-22 09:46 UTC, Dmytro1918 reviewed
Changes were applied.

2024-02-22 09:48 UTC, tihon-veliar approved these changes

2024-02-22 09:48 UTC, merged